### ISSUE TITLE
not able to open output files - 404

### ISSUE THREAD

**Issue by saulobejo** [antonkulaga/cromwell-client#4]
hello,

I'm getting 404 when I try to get output files.

<http://10.142.0.5:8001/cromwell/cromwell-executions/WholeGenomeGermlineSingleSample/93594b55-4e1f-4831-99bd-0a6df7f9a70a/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/bde5e5b5-e4cd-4cf2-b4f8-1d2d9db6df26/call-CollectUnsortedReadgroupBamQualityMetrics/shard-0/execution/stdout>

Inside the docker container it works:

```sh
ls /data/cromwell-executions/WholeGenomeGermlineSingleSample/93594b55-4e1f-4831-99bd-0a6df7f9a70a/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/bde5e5b5-e4cd-4cf2-b4f8-1d2
d9db6df26/call-CollectUnsortedReadgroupBamQualityMetrics/shard-0/execution/stdout
```
The storage is mounted inside from a blob storage

```yaml
version: '3.8'
services:
  cromwell-client:
    image: quay.io/comp-bio-aging/cromwell-web:latest
    environment:
      - CROMWELL=http://cromwell:8000
      - CROMWELL_LOGS=/data/sources/cromwell-client/logs
    ports:
      - 8001:8001
    volumes:
      - /mnt/coab/cromwell-executions:/data/cromwell-executions:ro
      - /mnt/coab/cromwell-workflow-logs:/data/cromwell-workflow-logs:ro

networks:
  default:
    name: cromwellazure_default
    external: true
```
